include classpath("application.conf")

queues {
  GamificationQueue {
    defaultVisibilityTimeout = 10 seconds
    delay = 5 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "GamificationQueue-dead-letters"
      maxReceiveCount = 3 // from 1 to 1000
    }
  }
}

aws {
  region = us-east-2
  accountId = 000000000000
}
