services:
  # --- TOR SERVICE (Bypass network blocks) ---
  tor:
    image: alpine
    container_name: lnbits-tor
    command: sh -c "apk add --no-cache tor && tor --SocksPort 0.0.0.0:9050 --DataDirectory /tmp/tor --CookieAuthentication 0"
    restart: always

  # --- 1. LND (Modo Neutrino) ---
  lnd:
    image: lightninglabs/lnd:v0.17.3-beta
    container_name: lnbits-lnd
    restart: always
    environment:
      - GODEBUG=netdns=go
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./lnd-data:/root/.lnd
    ports:
      - "8080:8080"
      - "10009:10009"
      - "9735:9735"
    command: >
      --bitcoin.active
      --bitcoin.mainnet
      --bitcoin.node=neutrino
      --neutrino.addpeer=35.190.38.75
      --neutrino.addpeer=165.227.29.135
      --neutrino.addpeer=50.112.125.89
      --neutrino.feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json
      --rpclisten=0.0.0.0:10009
      --restlisten=0.0.0.0:8080
      --listen=0.0.0.0:9735
      --tlsextradomain=lnd
      --tlsextradomain=lnbits-lnd
      --tlsextraip=0.0.0.0
      --tlsextraip=127.0.0.1
      --wallet-unlock-password-file=/root/.lnd/password.txt
      --debuglevel=info
      --tor.active
      --tor.socks=tor:9050
      --tor.control=tor:9051
    depends_on:
      - tor

  # --- 3. LNBITS ---
  lnbits:
    image: lnbits/lnbits:v1.4.1-rc2
    container_name: lnbits-main
    restart: always
    ports:
      - "7777:5000"
    env_file:
      - .env
    depends_on:
      - lnd
      - tor
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./data:/app/data
      - ./lnd-data:/lnd-data-ro:ro
      - ./extensions:/app/lnbits/extensions
