// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Biterva API",
    "version": "1"
  },
  "paths": {
    "/login": {
      "post": {
        "summary": "userLogin",
        "description": "",
        "operationId": "userLogin.post.login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login successful",
            "schema": {
              "$ref": "#/definitions/UserResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/prices": {
      "get": {
        "summary": "getPrice",
        "description": "",
        "operationId": "getPrice.get.prices",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/user": {
      "get": {
        "summary": "getUser",
        "description": "",
        "operationId": "getUser.get.user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/signup": {
      "post": {
        "summary": "userSignup",
        "description": "",
        "operationId": "userSignup.post.signup",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SignupRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User created successfully",
            "schema": {
              "$ref": "#/definitions/UserResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/invoice": {
      "post": {
        "summary": "createInvoice",
        "description": "",
        "operationId": "createInvoice.post.invoice",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateInvoiceRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Invoice created successfully. Returns payment request and hash.",
            "schema": {
              "$ref": "#/definitions/CreateInvoiceResponse"
            }
          },
          "400": {
            "description": "Bad Request. Missing userId or amount.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "User not found.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/webhook": {
      "post": {
        "summary": "paymentWebhook",
        "description": "",
        "operationId": "paymentWebhook.post.webhook",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PaymentWebhookRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Webhook processed successfully.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/pay": {
      "post": {
        "summary": "payInvoice",
        "description": "",
        "operationId": "payInvoice.post.pay",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PayInvoiceRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Payment successful.",
            "schema": {
              "$ref": "#/definitions/PayInvoiceResponse"
            }
          },
          "400": {
            "description": "Bad Request. Insufficient funds or invalid invoice.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "User not found.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/withdraw-nequi": {
      "post": {
        "summary": "withdrawToNequi",
        "description": "",
        "operationId": "withdrawToNequi.post.withdraw-nequi",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/WithdrawRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Withdrawal successful.",
            "schema": {
              "$ref": "#/definitions/WithdrawResponse"
            }
          },
          "400": {
            "description": "Bad Request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "User not found.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "502": {
            "description": "Trokera Error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "SignupRequest": {
      "properties": {
        "email": {
          "title": "SignupRequest.email",
          "type": "string"
        },
        "name": {
          "title": "SignupRequest.name",
          "type": "string"
        },
        "password": {
          "title": "SignupRequest.password",
          "type": "string"
        }
      },
      "required": [
        "email",
        "name",
        "password"
      ],
      "additionalProperties": false,
      "title": "SignupRequest",
      "examples": "{\n\"email\": \"user@example.com\"\n}",
      "type": "object"
    },
    "LoginRequest": {
      "properties": {
        "email": {
          "title": "LoginRequest.email",
          "type": "string"
        },
        "password": {
          "title": "LoginRequest.password",
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ],
      "additionalProperties": false,
      "title": "LoginRequest",
      "examples": "{\n\"email\": \"user@example.com\",\n\"password\": \"secretpassword\"\n}",
      "type": "object"
    },
    "UserResponse": {
      "properties": {
        "message": {
          "title": "UserResponse.message",
          "type": "string"
        },
        "user": {
          "properties": {
            "id": {
              "title": "UserResponse.user.id",
              "type": "string"
            },
            "email": {
              "title": "UserResponse.user.email",
              "type": "string"
            },
            "name": {
              "title": "UserResponse.user.name",
              "type": "string"
            },
            "walletId": {
              "title": "UserResponse.user.walletId",
              "type": "string"
            }
          },
          "required": [
            "id",
            "email",
            "name",
            "walletId"
          ],
          "additionalProperties": false,
          "title": "UserResponse.user",
          "type": "object"
        }
      },
      "required": [
        "message",
        "user"
      ],
      "additionalProperties": false,
      "title": "UserResponse",
      "examples": "{\n\"message\": \"User created successfully\",\n\"user\": {\n\"id\": \"696d8f7631fb957bc0d01a45\",\n\"email\": \"user@example.com\",\n\"name\": \"Jose Berna\",\n\"walletId\": \"wallet123\"\n}\n}",
      "type": "object"
    },
    "ErrorResponse": {
      "properties": {
        "message": {
          "title": "ErrorResponse.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "ErrorResponse",
      "examples": "{\n\"message\": \"Invalid input data\"\n}",
      "type": "object"
    },
    "CreateInvoiceRequest": {
      "properties": {
        "userId": {
          "title": "CreateInvoiceRequest.userId",
          "type": "string"
        },
        "amount": {
          "title": "CreateInvoiceRequest.amount",
          "type": "number"
        },
        "memo": {
          "title": "CreateInvoiceRequest.memo",
          "type": "string"
        },
        "fiatAmount": {
          "title": "CreateInvoiceRequest.fiatAmount",
          "type": "number"
        },
        "fiatCurrency": {
          "title": "CreateInvoiceRequest.fiatCurrency",
          "type": "string"
        }
      },
      "required": [
        "userId",
        "amount",
        "memo"
      ],
      "additionalProperties": false,
      "title": "CreateInvoiceRequest",
      "examples": "{\n\"userId\": \"696d8f7631fb957bc0d01a45\",\n\"amount\": 777,\n\"memo\": \"First Invoice\"\n}",
      "type": "object"
    },
    "CreateInvoiceResponse": {
      "properties": {
        "paymentRequest": {
          "title": "CreateInvoiceResponse.paymentRequest",
          "type": "string"
        },
        "paymentHash": {
          "title": "CreateInvoiceResponse.paymentHash",
          "type": "string"
        }
      },
      "required": [
        "paymentRequest",
        "paymentHash"
      ],
      "additionalProperties": false,
      "title": "CreateInvoiceResponse",
      "examples": "{\n\"paymentRequest\": \"lnbc1...\",\n\"paymentHash\": \"a1b2c3d4...\"\n}",
      "type": "object"
    },
    "PaymentWebhookRequest": {
      "properties": {
        "payment_hash": {
          "title": "PaymentWebhookRequest.payment_hash",
          "type": "string"
        },
        "amount": {
          "title": "PaymentWebhookRequest.amount",
          "type": "number"
        },
        "checking_id": {
          "title": "PaymentWebhookRequest.checking_id",
          "type": "string"
        },
        "memo": {
          "title": "PaymentWebhookRequest.memo",
          "type": "string"
        },
        "bolt11": {
          "title": "PaymentWebhookRequest.bolt11",
          "type": "string"
        }
      },
      "required": [
        "payment_hash"
      ],
      "additionalProperties": false,
      "title": "PaymentWebhookRequest",
      "examples": "{\n\"payment_hash\": \"a1b2c3d4...\"\n}",
      "type": "object"
    },
    "PayInvoiceRequest": {
      "properties": {
        "userId": {
          "title": "PayInvoiceRequest.userId",
          "type": "string"
        },
        "invoice": {
          "title": "PayInvoiceRequest.invoice",
          "type": "string"
        },
        "fiatAmount": {
          "title": "PayInvoiceRequest.fiatAmount",
          "type": "number"
        },
        "fiatCurrency": {
          "title": "PayInvoiceRequest.fiatCurrency",
          "type": "string"
        }
      },
      "required": [
        "userId",
        "invoice"
      ],
      "additionalProperties": false,
      "title": "PayInvoiceRequest",
      "examples": "{\n\"userId\": \"696d8f7631fb957bc0d01a45\",\n\"invoice\": \"lnbc1...\"\n}",
      "type": "object"
    },
    "PayInvoiceResponse": {
      "properties": {
        "paymentHash": {
          "title": "PayInvoiceResponse.paymentHash",
          "type": "string"
        }
      },
      "required": [
        "paymentHash"
      ],
      "additionalProperties": false,
      "title": "PayInvoiceResponse",
      "examples": "{\n\"paymentHash\": \"a1b2c3d4...\"\n}",
      "type": "object"
    },
    "WithdrawRequest": {
      "properties": {
        "userId": {
          "title": "WithdrawRequest.userId",
          "type": "string"
        },
        "amountSats": {
          "title": "WithdrawRequest.amountSats",
          "type": "number"
        },
        "nequi": {
          "title": "WithdrawRequest.nequi",
          "type": "string"
        },
        "observations": {
          "title": "WithdrawRequest.observations",
          "type": "string"
        },
        "saveNequi": {
          "title": "WithdrawRequest.saveNequi",
          "type": "boolean"
        }
      },
      "required": [
        "userId",
        "amountSats"
      ],
      "additionalProperties": false,
      "title": "WithdrawRequest",
      "examples": "{\n\"userId\": \"696d8f7631fb957bc0d01a45\",\n\"amountSats\": 1000\n}",
      "type": "object"
    },
    "WithdrawResponse": {
      "properties": {
        "message": {
          "title": "WithdrawResponse.message",
          "type": "string"
        },
        "transactionId": {
          "title": "WithdrawResponse.transactionId",
          "type": "string"
        },
        "trokeraChargeId": {
          "title": "WithdrawResponse.trokeraChargeId",
          "type": "string"
        }
      },
      "required": [
        "message",
        "transactionId",
        "trokeraChargeId"
      ],
      "additionalProperties": false,
      "title": "WithdrawResponse",
      "examples": "{\n\"message\": \"Withdrawal initiated\",\n\"transactionId\": \"tx-123\",\n\"trokeraChargeId\": \"charge-456\"\n}",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "host": "localhost:3001",
  "schemes": [
    "http"
  ]
};